import type { EnvEntry } from './EnvParser.js';

export interface GeneratorOptions {
	envSource: 'process.env' | 'import.meta.env';
	typeName: string;
	generateGetEnvs: boolean;
}

export class CodeGenerator {
	constructor(private options: GeneratorOptions) {}

	generate(entries: EnvEntry[]): string {
		const parts = [
			this.buildHeader(),
			"import { z } from 'zod';",
			'',
			this.buildEnvNames(entries),
			'',
			this.buildSchema(entries),
			'',
			this.buildTypeAlias(),
		];

		if (this.options.generateGetEnvs) {
			parts.push('', this.buildGetEnvs());
		}

		return parts.join('\n') + '\n';
	}

	private buildHeader(): string {
		return '// Auto-generated by zodenv — DO NOT EDIT';
	}

	private buildEnvNames(entries: EnvEntry[]): string {
		const keys = entries.map((e) => `'${e.key}'`).join(', ');
		return `export const ENV_NAMES = [${keys}] as const;`;
	}

	private buildSchema(entries: EnvEntry[]): string {
		const lines = entries.map((e) => `\t${e.key}: ${this.entryToZodExpression(e)},`);
		return `export const envSchema = z.object({\n${lines.join('\n')}\n});`;
	}

	private buildTypeAlias(): string {
		return `export type ${this.options.typeName} = z.infer<typeof envSchema>;`;
	}

	private buildGetEnvs(): string {
		const source = this.options.envSource;
		const envAccess = source === 'import.meta.env' ? 'import.meta.env[name]' : 'process.env[name]';

		return [
			`export const getEnvs = (): ${this.options.typeName} => {`,
			`\tconst raw = Object.fromEntries(ENV_NAMES.map((name) => [name, ${envAccess}]));`,
			`\treturn envSchema.parse(raw);`,
			`};`,
		].join('\n');
	}

	entryToZodExpression(entry: EnvEntry): string {
		if (entry.type === 'boolean') {
			return `z.enum(['true', 'false']).transform(v => v === 'true')`;
		}

		if (entry.type === 'number') {
			return `z.coerce.number()`;
		}

		// string
		if (entry.defaultValue !== undefined) {
			return `z.string().default('${entry.defaultValue}')`;
		}

		if (entry.isOptional) {
			return `z.string().optional()`;
		}

		return `z.string().min(1)`;
	}
}
